### ISSUE TITLE
"uncaught error"?

### ISSUE THREAD

**Issue by TTT2866** [J0ker98/Omegle-Bot#1]
Looks like a great code so far by reading the comments but I can't seem to get it to work. This is the error when the page runme.php loads

`Fatal error: Uncaught Error: Call to undefined function eregi_replace() in C:\Users\HUM0014\Desktop\PHPserver\omegle\php.omegle.php:27 Stack trace: #0 C:\Users\HUM0014\Desktop\PHPserver\omegle\runme.php(14): OmBot->conn() #1 {main} thrown in C:\Users\HUM0014\Desktop\PHPserver\omegle\php.omegle.php on line 27`

And this is in terminal (if it makes any difference)

`[Tue Nov 20 17:45:06 2018] ::1:15771 [200]: /omegle/runme.php - Uncaught Error: Call to undefined function eregi_replace() in C:\Users\HUM0014\Desktop\PHPserver\omegle\php.omegle.php:27
Stack trace:
#0 C:\Users\HUM0014\Desktop\PHPserver\omegle\runme.php(14): OmBot->conn()
#1 {main}
  thrown in C:\Users\HUM0014\Desktop\PHPserver\omegle\php.omegle.php on line 27`

any idea?

**Comment by J0ker98** [comment]
You are running the program with php 7, you should use php 5.3
