### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by sebastienlorentz** [J0ker98/Omegle-Bot#5]
Tried running on Mac Os
got this:
Fatal error: Uncaught Error: Call to undefined function eregi_replace() in /Users/Admin 1/Desktop/Omegle-Bot-master/php.omegle.php:27
Stack trace:
#0 /Users/Admin 1/Desktop/Omegle-Bot-master/runme.php(14): OmBot->conn()
#1 {main}
  thrown in /Users/Admin 1/Desktop/Omegle-Bot-master/php.omegle.php on line 27
MacBook-Pro-4:Omegle-Bot-master Admin$

**Comment by LucaMPereira** [comment]
First of sorry for a late reply. Second, Is the name of the bot the same in both files?

**Comment by J0ker98** [comment]
> Tried running on Mac Os
> got this:
> Fatal error: Uncaught Error: Call to undefined function eregi_replace() in /Users/Admin 1/Desktop/Omegle-Bot-master/php.omegle.php:27
> Stack trace:
> #0 /Users/Admin 1/Desktop/Omegle-Bot-master/runme.php(14): OmBot->conn()
> #1 {main}
> thrown in /Users/Admin 1/Desktop/Omegle-Bot-master/php.omegle.php on line 27
> MacBook-Pro-4:Omegle-Bot-master Admin$

I updated the code, try now
